### ISSUE TITLE
recon hosts-hosts virustotal returns an error

### ISSUE THREAD

**Issue by fakemaria** [lanmaster53/recon-ng-marketplace#189]
**To save some time, have you:**
- [ ] Checked the [wiki](https://github.com/lanmaster53/recon-ng/wiki) 
- [ ] Checked previously answered [questions](https://github.com/lanmaster53/recon-ng-marketplace/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3Aquestion)

**Please ask the question below**  
I have the api key added , this is the log with verbosity set to 2:

[*] ========================= REQUEST =========================
url:    https://www.virustotal.com/vtapi/v2/ip-address/report?ip=[removed]
method: GET /vtapi/v2/ip-address/report?ip=[removed]
header: User-Agent: Recon-ng/v5
header: Accept-Encoding: gzip, deflate
header: Accept: */*
header: Connection: keep-alive
[*] ========================= RESPONSE =========================
status: 403 Forbidden
header: Content-Type: text/html; charset=utf-8
header: Cache-Control: no-cache
header: X-Cloud-Trace-Context: d04632992c22d5a0b9b61d9b21a487a1
header: Date: Mon, 21 Dec 2020 11:41:55 GMT
header: Server: Google Frontend
header: Content-Length: 0
------------------------------------------------------------
Traceback (most recent call last):                                                                                
  File "/usr/share/recon-ng/recon/core/module.py", line 347, in do_run                                            
    self.run()                                                                                                    
  File "/usr/share/recon-ng/recon/core/module.py", line 341, in run                                               
    self.module_run(*params)                                                                                      
  File "/root/.recon-ng/modules/recon/hosts-hosts/virustotal.py", line 24, in module_run                          
    if resp.json() and 'resolutions' in resp.json().keys():                                                       
  File "/usr/lib/python3/dist-packages/requests/models.py", line 898, in json                                     
    return complexjson.loads(self.text, **kwargs)                                                                 
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads                                
    return _default_decoder.decode(s)                                                                             
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode                                
    obj, end = self.raw_decode(s)                                                                                 
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode                            
    return self.scan_once(s, idx=_w(s, idx).end())                                                                
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                      
------------------------------------------------------------                                                      
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

**Comment by fakemaria** [comment]
closed: after closing and reopening and doing a marketplace install all works fine
