### ISSUE TITLE
recon/contacts-credentials/hibp_breach error message

### ISSUE THREAD

**Issue by gsebas18** [lanmaster53/recon-ng-marketplace#78]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/contacts-credentials/hibp_breach.py

**Bug Description**
When running recon/contacts-credentials/hibp_breach the following error pops up:
```
[!] String indices must be integers.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.
```

Edit: More info. I set VERBOSITY to 2.
```
[recon-ng][default][hibp_breach] > run
[*] ========================= REQUEST =========================
url:    https://haveibeenpwned.com/api/v3/breachedaccount/gsebas94%40gmail.com?truncateResponse=false
method: GET /api/v3/breachedaccount/gsebas94%40gmail.com?truncateResponse=false
header: User-Agent: Recon-ng/v5
header: Accept-Encoding: gzip, deflate
header: Accept: */*
header: Connection: keep-alive
[*] ========================= RESPONSE =========================
status: 401 Unauthorized
header: Date: Wed, 13 Nov 2019 05:32:25 GMT
header: Content-Type: application/json
header: Content-Length: 78
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d02043f02a5e86b6ddcd480dc79dfa5cd1573623145; expires=Thu, 12-Nov-20 05:32:25 GMT; path=/; domain=.haveibeenpwned.com; HttpOnly
header: Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
header: X-Content-Type-Options: nosniff
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Vary: Accept-Encoding
header: Server: cloudflare
header: CF-RAY: 534e5d735c3def0a-MIA
body:   b'{ "statusCode": 401, "message": "Access denied due to missing hibp-api-key." }'
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/recon-ng/recon/core/module.py", line 291, in do_run
    self.module_run(*params)
  File "/root/.recon-ng/modules/recon/contacts-credentials/hibp_breach.py", line 35, in module_run
    self.alert(f"{account} => Breach found! Seen in the {breach['Name']} breach that occurred on "
TypeError: string indices must be integers
------------------------------------------------------------
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.
[*] DATABASE => /root/.recon-ng/workspaces/default/data.db
[*] QUERY => INSERT OR REPLACE INTO dashboard (module, runs) VALUES ('recon/contacts-credentials/hibp_breach', COALESCE((SELECT runs FROM dashboard WHERE module='recon/contacts-credentials/hibp_breach')+1, 1))

```

**Steps to Reproduce**
\[Steps to reproduce the behavior:
1. Set SOURCE option with whatever email address
2. Issue 'run' command

**Expected Behavior**
Displays results

**Screenshots**
![image](https://user-images.githubusercontent.com/22620063/68719726-dff8e080-057a-11ea-84dc-ce06bc429650.png)

**Additional Context**
Running on recon-ng v5.0.1
Running on recon/contacts-credentials/hibp_breach.py v1.2

**Comment by cam-barts** [comment]
@gsebas18 This is almost certainly because hibp has changed their api to enforce api authentication and paid api keys. See here https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/. New pricing model is $3.50 per million calls.

**Comment by griddd** [comment]
cam-barts, I believe you are incorrect.  I'm seeing the same results as gsebas18, and I have an API key.  It appears as though the module is not passing the required "hibp-api-key" header in the HTTP request.

**Comment by griddd** [comment]
Please ignore my last comment.  I'm running on Kali Linux, and updating fixed the problem.

Feel like such a goof :)

**Comment by lanmaster53** [comment]
Sounds like this is resolved. Thanks!
